services:
  - type: web
    name: room-food
    runtime: node
    buildCommand: cd code && NPM_CONFIG_PRODUCTION=false npm ci && npm run build:ssr
    startCommand: cd code && npm run serve:ssr:RoomFood
    env: node
    plan: free
    envVars:
      - key: PORT
        value: 10000

